name: stor_paper
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  google_sign_in: ^5.0.2
  flutter_auth_buttons: ^0.10.0
  provider:
  flutter_facebook_login: ^3.0.0
  rxdart: ^0.26.0
  image_downloader:
  rflutter_alert: ^2.0.2
  cloud_firestore: ^2.0.0
  shared_preferences: ^2.0.5
  firebase_storage: ^8.0.5
  memoize: ^3.0.0
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  flushbar: ^1.10.4
  flutter_swiper: ^1.1.6
  transformer_page_view: ^0.1.6
  sliding_up_panel: ^2.0.0+1
  parallax_image: 
  flutter_parallax: "^0.1.2"
  sliding_panel: ^1.3.2
  in_app_purchase: ^0.5.2
  permission_handler: ^7.1.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.0.0
  connectivity: ^3.0.3
  flutter_staggered_animations: ^1.0.0
  dartz: ^0.9.2
  freezed_annotation: ^0.14.1
  
dev_dependencies:
  freezed: ^0.14.1+3
  build_runner: ^2.0.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/image1.jpg
  - images/image2.jpg
  - images/image3.jpg
  - images/ig.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baloo
      fonts:
        - asset: fonts/Baloo-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Regular.ttf  
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Bold.ttf
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Bold.ttf
        - asset: fonts/Cinzel-Regular.ttf         
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
